# # DuckDB configuration
# duckdb:
#   database: "${data_dir}/metadata.db"
  
# # Vector store (Chroma)
# vector_store:
#   type: "chroma"
#   host: "chroma"
#   port: 8000
#   collection: "document_chunks"
  
# # Graph database (Neo4j)
# graph_db:
#   type: "neo4j"
#   uri: "bolt://neo4j:7687"
#   user: "neo4j"
#   password: "${oc.env:NEO4J_PASSWORD,password}"
#   database: "documents"

# DuckDB configuration
duckdb:
  database: "${data_dir}/metadata.db"
  schema: "personal_rag"
  tables:
    documents:
      columns:
        - name: "doc_id"
          type: "VARCHAR"
          primary_key: true
        - name: "file_name"
          type: "VARCHAR"
          index: true
        - name: "file_extension"
          type: "VARCHAR"
        - name: "content_type"
          type: "VARCHAR[]"
        - name: "created_at"
          type: "TIMESTAMP"
        - name: "author"
          type: "VARCHAR"
        - name: "metadata"
          type: "JSON"
        - name: "persuasion_tags"
          type: "VARCHAR[]"
        - name: "text_content"
          type: "TEXT"
          
    chunks:
      columns:
        - name: "chunk_id"
          type: "VARCHAR"
          primary_key: true
        - name: "doc_id"
          type: "VARCHAR"
          foreign_key: "documents.doc_id"
        - name: "text_chunk"
          type: "TEXT"
        - name: "tag_context"
          type: "VARCHAR[]"
          
    pipeline_events:
      columns:
        - name: "event_id"
          type: "VARCHAR"
          primary_key: true
        - name: "doc_id"
          type: "VARCHAR"
          foreign_key: "documents.doc_id"
        - name: "event_type"
          type: "VARCHAR"
        - name: "event_timestamp"
          type: "TIMESTAMP"
        - name: "event_data"
          type: "JSON"
  
# Vector store (Chroma)
vector_store:
  type: "chroma"
  host: "chroma"
  port: 8000
  collections:
    document_chunks:
      embedding_function: "sentence-transformers/all-MiniLM-L6-v2"
      dimension: 384
      metadata_fields:
        - "doc_id"
        - "chunk_id"
        - "content_type"
        - "tag_context"
        - "source_page"
        - "creation_date"
    query_history:
      embedding_function: "sentence-transformers/all-MiniLM-L6-v2"
      dimension: 384
  
# Graph database (Neo4j)
graph_db:
  type: "neo4j"
  uri: "bolt://neo4j:7687"
  user: "neo4j"
  password: "${oc.env:NEO4J_PASSWORD,password}"
  database: "documents"
  
  # Node types
  nodes:
    Document:
      properties:
        - "doc_id"
        - "file_name"
        - "content_type"
        - "created_at"
        - "author"
    
    EmailThread:
      properties:
        - "thread_id"
        - "subject"
        - "participant_count"
    
    Person:
      properties:
        - "name"
        - "email"
        - "role"
    
    Topic:
      properties:
        - "name"
        - "relevance_score"
    
  # Relationship types
  relationships:
    CONTAINS:
      from: "Document"
      to: "Topic"
      properties:
        - "relevance_score"
    
    AUTHORED_BY:
      from: "Document"
      to: "Person"
      properties:
        - "timestamp"
    
    REPLIES_TO:
      from: "Document"
      to: "Document"
      properties:
        - "timestamp"
    
    REFERENCES:
      from: "Document"
      to: "Document"
      properties:
        - "reference_type"
        - "relevance"
    
    BELONGS_TO:
      from: "Document"
      to: "EmailThread"
      properties:
        - "position_in_thread"