# # version: '3.8'

# services:
#   processor:
#     volumes:
#       - ..:/workspace:cached
#     command: sleep infinity
#     environment:
#       - PYTHONPATH=/workspace
    
#   api:
#     volumes:
#       - ..:/workspace:cached
#     command: sleep infinity
    
#   llm:
#     volumes:
#       - ..:/workspace:cached
#     command: sleep infinity

# version: '3.8'

services:
  processor:
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
    
  api:
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - LOG_LEVEL=debug
    
  llm:
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - LOG_LEVEL=debug

  # Development-only services
  devtools:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
    ports:
      - "8888:8888"  # For Jupyter notebooks if needed

  # Database admin tools
  neo4j-admin:
    image: neo4j:5.13.0
    profiles: ["admin"]
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_mode=READ_ONLY
    volumes:
      - neo4j_data:/data