# services/processor/conf/config.yaml
# Alternative approach: self-contained configuration

defaults:
  - _self_

# Application configuration
app_name: "personal-rag-llm"
app_version: "0.2.0"
data_dir: "${oc.env:DATA_DIR,/data}"
cache_dir: "${oc.env:CACHE_DIR,/data/cache}"
log_level: "${oc.env:LOG_LEVEL,INFO}"

# Processing configuration
max_workers: 4

# Pipeline configuration
pipeline:
  pdf:
    engine: "pymupdf"
    extract_images: true
    perform_ocr: true
    enable_document_extractor: true
    enable_email_extractor: true
    enable_presentation_extractor: true
  
  ocr:
    engine: "tesseract"
    languages: "eng"
    tesseract_config: "--psm 3"

# Storage configuration
storage:
  duckdb:
    database: "${data_dir}/metadata.db"
  vector_store:
    host: "localhost"
    port: 8000
  graph_db:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    database: "neo4j"

# VLM Configuration - directly embedded instead of using defaults
vlm:
  # Environment-controlled enable/disable
  enabled: ${oc.env:VLM_ENABLED,false}
  processor_type: "cpu_optimized"
  
  # Timeout configuration optimized for CPU processing
  base_timeout: 180
  min_timeout: 60
  max_timeout: 600
  adaptive_timeouts: true
  timeout_multiplier: 1.8
  
  # Retry configuration
  max_retries: 2
  retry_backoff_base: 2
  retry_backoff_max: 30
  
  # CPU-specific optimizations
  max_pages_per_document: 3
  max_documents_parallel: 1
  image_size_limit: [1024, 1024]
  image_compression_quality: 85
  use_simplified_prompts: true
  max_response_tokens: 512
  
  # Progress monitoring
  enable_progress_logging: true
  log_performance_metrics: true
  log_timeout_adjustments: true
  
  # LLaVA configuration
  llava:
    model: "llava:7b"
    api_endpoint: "http://localhost:11434"
    model_options:
      temperature: 0.1
      top_p: 0.9
      repeat_penalty: 1.1
      num_ctx: 2048
      num_predict: 512
      num_thread: 4
  
  # Fallback configuration
  fallback:
    enabled: true
    confidence_threshold: 0.3
    timeout_fallback: true
    error_fallback: true
    min_content_length: 20
    max_processing_time_ratio: 2.0
  
  # Prompt configuration
  prompts:
    simplified: |
      Analyze this document page and respond with JSON only:
      
      {
        "type": "email|report|presentation|chart|table|mixed",
        "confidence": 0.8,
        "content": "main content summary in 1-2 sentences"
      }
      
      Keep response brief.
    
    standard: |
      Analyze this document page and provide structured information.
      
      Return JSON format:
      {
        "content_type": "email|presentation|report|chart|table|mixed",
        "confidence": 0.8,
        "layout": "brief layout description",
        "text_content": "key text content",
        "visual_elements": [{"type": "table", "description": "brief description"}]
      }
      
      Focus on accuracy over detail.
  
  # Performance tracking
  performance_tracking:
    enabled: true
    track_response_times: true
    track_success_rates: true
    track_timeout_effectiveness: true
    target_success_rate: 0.8
    target_avg_response_time: 120
    adjust_timeouts_after: 5
    increase_timeout_if_success_below: 0.6
    decrease_timeout_if_success_above: 0.9