# services/processor/conf/enhanced_config.yaml
defaults:
  - _self_
  - extractors: enhanced
  - classifiers: default
  - embedders: default
  - storage: default

# Enhanced processing configuration
processing:
  input_dir: "${data_dir}/input"
  output_dir: "${data_dir}/processed"
  max_workers: 4
  max_file_size_mb: 200
  
  # Extended file type support
  supported_file_types:
    # Documents
    - pdf
    - docx
    - doc
    # Spreadsheets
    - xlsx
    - xls
    - csv
    # Presentations
    - pptx
    - ppt
    # Images
    - png
    - jpg
    - jpeg
    - tiff
    - bmp
    # Text
    - txt
    - md

# Image processing configuration
image:
  ocr:
    engine: "tesseract"
    languages: "eng"
    tesseract_config: "--oem 3 --psm 11"
    preprocess: true
  analysis:
    detect_charts: true
    detect_diagrams: true
    detect_floor_plans: true
    extract_data_from_charts: true

# Office document configuration
office:
  excel:
    extract_all_sheets: true
    include_formulas: false
    max_preview_rows: 100
    extract_statistics: true
  word:
    extract_tables: true
    extract_metadata: true
  powerpoint:
    extract_notes: true
    extract_charts: true
    detect_visual_slides: true

# Enhanced chunking for different content types
chunker:
  # Image content chunking
  image_chunk_size: 1000  # Larger for image descriptions
  image_chunk_overlap: 200
  
  # Spreadsheet chunking
  spreadsheet_chunk_size: 800
  spreadsheet_chunk_overlap: 100
  preserve_table_structure: true
  
  # Default chunking
  default_chunk_size: 500
  default_chunk_overlap: 50

# Storage configuration
storage:
  duckdb:
    database: "${data_dir}/enhanced_metadata.db"
    schema: "rag_system"
    
  vector_store:
    host: "chroma"
    port: 8000
    embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
    
  graph_db:
    uri: "bolt://neo4j:7687"
    user: "neo4j"
    password: "${oc.env:NEO4J_PASSWORD,password}"
    database: "documents"