name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd services/processor && poetry install
      - name: Lint
        run: |
          cd services/processor && poetry run pylint src
      - name: Test
        run: |
          cd services/processor && poetry run pytest

  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
          cd services/api && go mod download
      - name: Lint
        run: |
          cd services/api && go vet ./...
      - name: Test
        run: |
          cd services/api && go test ./...

  build-images:
    needs: [test-python, test-go]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push images
        run: |
          docker-compose -f docker/docker-compose.yml build
          # Add push commands when ready for deployment